name: Call workflow
on: 
  workflow_dispatch:
   inputs:
    node-version:        
      required: false
      type: string
      default: 'lts/*'

jobs:
  call-reusable:
    runs-on: self-hosted
    uses: ./.github/workflows/reusable.yml
    with:
      node-version: ${{inputs.node-version}}